version: "3"

services:
  
  app:
    image: shengli/nginx-hello
    ports:
      - 6100:80
    networks:
      - nginxdemo
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager ]

  nginx:
    image: shengli/nginx-basic
    ports:
      - 6101:80
    networks:
      - nginxdemo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager ]

networks:
  nginxdemo:        
