version: "3"

services:
  
  nginx:
    image: shengli/nginx-http-https
    ports:
      - 6101:80
    networks:
      - nginxdemo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager ]

networks:
  nginxdemo:        
