version: "3"

services:
  
  postgres-app:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - postgresdemo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager ]

networks:
  postgresdemo:        
